### PR TITLE
Pull selectively

### PR DESCRIPTION
**Pull request by solsson**
For https://github.com/Yolean/build-contract/issues/12

Or we have to use exact tags/sha256 for all upstream images everywhere.

Building experimental [solsson/build-contract-push](https://hub.docker.com/r/solsson/build-contract-push/) from this branch.

### CODE REVIEW

**Comment by solsson** [comment]
`solsson/build-contract-push:pr13` is the experimental build

**Comment by atamon** [comment]
I guess we could disable pulls via some option.

I haven't really understood this myself, but as you said an image that depends on a locally built image won't need to pull. But I guess that is only true if the "base image" inside the repository specifies a strict version (like node:6.8.0 for example).

**Comment by solsson** [comment]
Rebased, previous was 6a5a570e59ed254c1aeadb2be97399960afe244b

**Comment by solsson** [comment]
Had another case of this now, with a test container doing `FROM localhost:5000/yolean/my-service` and build-contract declaring the build dependency:
```
  my-service:
    build:
      context: ../
    image: localhost:5000/yolean/my-service:${PUSH_TAG-latest}
  my-test:
    depends_on:
      - my-service
    build: ./my-test
```

Didn't work with the regular build-contract image, but with `sha256:ca31f62dd6d149353064b2160dfa7a56b1815aa8cd60c4ff6b52707338f7ddd1` from this PR.

**Comment by solsson** [comment]
Reminder: this issue is a major gotcha. I just got an old build from a new git commit. Turns out I was using `solsson/build-contract@sha256:606333fe1c55326509e6ad4788113a17c58d2957422defb44190b7a711551ab9` instead of `solsson/build-contract@sha256:ca31f62dd6d149353064b2160dfa7a56b1815aa8cd60c4ff6b52707338f7ddd1`.

Will change to `solsson/build-contract:pr13` with `imagePullPolicy: Always` for the modules that depend on this PR, so we don't accidentally upgrade.

**Comment by solsson** [comment]
I've rebased and built `solsson/build-contract@sha256:f01f8bc564477d882bbda0fcb15b8eef3118aae5031dc5ab5e2daaa64a183d40`

Also included a commit that was quite essential for #36.

@atamon We should use this build all over the place, and merge if not a lot breaks. That'll give us a single build-contract image to keep track of.

I've forgotten if there were any downside with d2a9cb1 or not.

**Comment by solsson** [comment]
Built from master now, with https://github.com/Yolean/docker-base/releases/tag/docker.node.9d02ee07572e98ce3db9018ac6ee2a70b12464498d3ea36aca0e9d6fb660eba7 

`solsson/build-contract@sha256:d7e7108e6e9d68a2b9afdefce68c7a9954edda9a5d09dea8fb4fc9148c940dc4`

**Pull request merged**
