### PR TITLE
Draft push implementation

### PR DESCRIPTION
**Pull request by atamon**

### CODE REVIEW

**Comment by solsson** [comment]
With other local builds referencing an `image:` in their `FROM` we probably need to have PUSH_TAG set to `latest` during test runs (and build) but to the actual value from external env during `docker-compose push`. But I need to do more testing.

**Comment by solsson** [comment]
:) I just suggested the exact same solution: https://github.com/Yolean/build-contract/commit/2e811ef8ba93b54a7831c5a777bd751861350e82

**Comment by solsson** [comment]
Building a separate image to evaluate this before we merge: https://hub.docker.com/r/solsson/build-contract-push/
 - Note that I've learned to avoid feature tags!

**Comment by solsson** [comment]
I think we can revert b34d457. We have to deal with `depends_on` and `FROM` by the book.

For example, with a downstream containing `FROM localhost:5000/yolean/httpd`, by duplicating that service in docker-compose.yml:
```
   httpd:
     build:
       context: ../
+    image: localhost:5000/yolean/httpd:latest
+  httpd-push:
+    extends:
+      service: httpd
     image: localhost:5000/yolean/httpd:$PUSH_TAG
     labels:
       com.yolean.build-target: ""
  httpd-downstream:
    build:
      context: ../dependent-build
    depends_on:
      - httpd
```

**Comment by solsson** [comment]
We will definitely need some kind of no-push flag, for local testing

**Comment by solsson** [comment]
Just built `solsson/build-contract-push`

Dogfood test fails for me:  ` docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/:/source -e PUSH_TAG=testing -e TEST_EXIT_CODE=0 solsson/build-contract-push:latest test`

**Comment by atamon** [comment]
I had to update the Dockerfile entrypoint and command lines.

Now I can get the expected behaviour locally:
```sh
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/:/source yolean/build-contract
  --- build-contract: This is a git repo and GIT_COMMIT=3c2f78b ---
```

```sh
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/:/source yolean/build-contract test
  --- build-contract: Offline run (builds will not docker pull and image: will not be pushed) ---
  --- build-contract: This is a git repo and GIT_COMMIT=3c2f78b ---
```

**Comment by solsson** [comment]
As usual, i didn't read the docs :) https://docs.docker.com/engine/reference/builder/#/entrypoint says "shell form prevents any CMD or run command line arguments from being used". Interestingly it also says "will not be the container’s PID 1 - and will not receive Unix signals". To me that sounds like all dockerfiles should use brackets ("exec form").

**Comment by solsson** [comment]
I've removed https://hub.docker.com/r/solsson/build-contract-push/ in favor of https://hub.docker.com/r/solsson/build-contract/

**Pull request merged**
